### ISSUE TITLE
install failing with python 3.12

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/MDAnalysisWorkshop2023#18]
the conda install of the workshop environment failed when I first tried it - I believe the issue is that it was pinning to python 3.12 but rise requires <3.12. It worked fine using mamba (which used 3.11). 

We could remove rise from the required packages (I believe it's only needed to turn the lecture notebook into slides) or pin python <3.12 in the environment file. We could also just change the install instructions to use mamba (which should also be faster).

**Comment by lilyminium** [comment]
Fixed in #24, kinda.
