### ISSUE TITLE
Remove emails?

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/MDAnalysisWorkshop2023#19]
The tutorial NBs all have emails of the authors, many of whom are not actually involved with this one -- do we want to remove them in case people start emailing them? (cc @yuxuanzhuang since you added yours too!)

**Comment by lilyminium** [comment]
Or we could potentially just remove authors per NB and use the repo author list, feels like this will just build up to a very long list over time

**Comment by fiona-naughton** [comment]
+1 to removing the emails, and to removing the author lists from the notebooks themselves - as you stay, that's potential to get very clunky. I'd vote for replacing it with a link to the AUTHORS file?
