### ISSUE TITLE
Assign reponsible lead

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/MDAnalysisWorkshop2023#2]
@MDAnalysis/coredevs (anyone that will be at some point likely to join in on a workshop), could I ask for someone to take responsibility for driving this repository forward?

I'm not asking for someone to do all the work, but someone that sees PRs / issues and distributes the load would be immensely appreciated here.

**Comment by micaela-matta** [comment]
🙋🏻‍♀️
